pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven {
            url 'http://developer.huawei.com/repo/'
            allowInsecureProtocol = true

        }
        maven {
            url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/"
            allowInsecureProtocol = true
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}
dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {url 'https://developer.huawei.com/repo/'
            allowInsecureProtocol = true
        }
        maven { url "https://indapps.in/maven-repo/"}
        maven {
            url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/"
            allowInsecureProtocol = true
        }
    }

}
rootProject.name = "Zyfoo_AI_30-03-26"
include ':app'

